### ISSUE TITLE
Fixed run-time JavaScript issue

### ISSUE THREAD

**Issue by guido1993** [OfficeDev/Word-Add-in-JavaScript-AddPopulateBindings#1]
Hello, I fixed a runtime issue that was preventing the app from running in Office 2016 Professional Plus. I am not aware if the same issue is showing up in Office 2013, as I can't really test it right now. I attached a screenshot of the problem to this message. The exception was being thrown when the "Add and Bind Control" button was clicked.

Basically, to fix it, I just removed the conditional "if" block, by removing this line: if (result.error.message == "The named item does not exist.")

This is line 30 in the file Home.js

Have a nice day,

Guido
![cattura](https://cloud.githubusercontent.com/assets/9572988/10278327/a578d24c-6b5c-11e5-8718-e612fb350446.PNG)

**Comment by DianeD** [comment]
Thanks Guido! Couldn't repro on my 2016 machine, but I'm trying it on a clean machine.

**Comment by guido1993** [comment]
Got any update? :)

**Comment by DianeD** [comment]
Hi Guido. I wasn't able to repro your issue, but I do have some changes: Check the code instead of the message, and Wrap the logic in the if clause. I want to get some more testing in before making it public. If you get a chance to test, please let me know if this works for you—or if not, what error you get. Thanks!

```
if (result.status === Office.AsyncResultStatus.Failed) {

    // If the named item doesn't exist, then add it.
    if (result.error.code === 3006) {
        var myOOXMLRequest = new XMLHttpRequest();
        var myXML;
        myOOXMLRequest.open('GET', '../../Snippets_BindAndPopulate/ContentControl.xml', false);
        myOOXMLRequest.send();

        if (myOOXMLRequest.status === 200) {
                        myXML = myOOXMLRequest.responseText;
        }
        Office.context.document.setSelectedDataAsync(myXML, { coercionType: 'ooxml' }, function (result) {
                        Office.context.document.bindings.addFromNamedItemAsync("MyContentControlTitle", "text", { id: 'myBinding' });
        });
    }
    else app.showNotification(result.error.name + " " + result.error.code, result.error.message);
}
```

**Comment by guido1993** [comment]
I tried again the previous code and I obtained the same result, over and over again.

The new code runs smoothly, both at adding the control and at replacing the control with the two other buttons :) I'd say that you fixed it great!

Thanks for the support,

Guido

**Comment by DianeD** [comment]
Great! Thanks again for your help, Guido!
